### ISSUE TITLE
Not available in Addons

### ISSUE THREAD

**Issue by DieProgrammIDE** [kodi-game/game.libretro.fsuae#6]
Hello,
i am trying to download this in Kodi 18.6 Leia with latest LibreElec on Raspberry Pi 4B+

It isn't available, and because the .so file is missing here i can't install it via zip!

**Comment by DieProgrammIDE** [comment]
?

**Comment by garbear** [comment]
fsuae fails to build for our scripting infra: https://github.com/kodi-game/kodi-game-scripting/blob/master/kodi_game_scripting/config.py#L73

if the build error gets fixed, this this repo will be updated and fsuae will show up in the repo. Until then, you can try the libretro buildbot repo by zachmorris
